# http://rkistner.github.com/android/2013/02/05/android-builds-on-travis-ci/
language: ruby
before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://ci.jruby.org/snapshots/master/jruby-jars-${MASTER}.gem
  - if [ "$JRUBY_JARS_VERSION" == "" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi
  - cat ~/.ssh/known_hosts
  - echo "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts

rvm:
  - "2.0.0"
#  - jruby-20mode # JRuby in 2.0 mode
#  - rbx-19mode

jdk:
  - oraclejdk7
#  - openjdk7

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=0
    - MASTER=9000.dev
  matrix:
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.4

    - ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.4

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.4

script:
    - rake install
    - ruboto setup -y -t android-10 -t android-$ANDROID_TARGET
    - source ~/.rubotorc
    - ruboto emulator -t $ANDROID_TARGET
    - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
