# http://rkistner.github.com/android/2013/02/05/android-builds-on-travis-ci/
language: ruby
before_install:
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=~/build/ruboto/ruboto/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --no-ui --force --filter tool,platform-tool,android-8,android-10,android-15,sysimg-15,android-16,sysimg-16

rvm:
#  - "1.8.7"
  - "1.9.3"
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - jruby-20mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode

jdk:
#   - oraclejdk6
   - oraclejdk7
#   - openjdk7
#   - openjdk6

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=1
#    - MASTER=`ls jruby-jars-*.dev.gem | tail -n 1 | cut -f 3 -d'-' | cut -f1-4 -d'.'`
  matrix:
#    - ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT
#    - ANDROID_TARGET=10 RUBOTO_PLATFORM=FROM_GEM    JRUBY_JARS_VERSION=$MASTER
#    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=$MASTER
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3
#    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.2
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT
#    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM    JRUBY_JARS_VERSION=$MASTER
#    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=$MASTER
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3
#    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.2
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT
#    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM    JRUBY_JARS_VERSION=$MASTER
#    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=$MASTER
#    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3
#    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.2

script: ./start_emulator.sh && ./run_tests.sh
