# http://rkistner.github.com/android/2013/02/05/android-builds-on-travis-ci/
language: ruby
before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://ci.jruby.org/snapshots/master/jruby-jars-${MASTER}.gem
  - if [ "$JRUBY_JARS_VERSION" == "" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi

rvm:
#  - "1.8.7"
#  - "1.9.3"
  - "2.0.0"
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - jruby-20mode # JRuby in 2.0 mode
#  - rbx-18mode
#  - rbx-19mode

jdk:
#  - oraclejdk6
  - oraclejdk7
#  - openjdk7
#  - openjdk6

env:
  global:
    - RUBOTO_UPDATE_EXAMPLES=0
    - MASTER=1.7.5.dev
  matrix:
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=10 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3

    - ANDROID_TARGET=16 RUBOTO_PLATFORM=CURRENT
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=FROM_GEM
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE
    - ANDROID_TARGET=16 RUBOTO_PLATFORM=STANDALONE JRUBY_JARS_VERSION=1.7.3

script:
    - rake install
    - ruboto setup -y -t android-$ANDROID_TARGET
    - source ~/.rubotorc
    - ./start_emulator.sh
    - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
