language: ruby
before_install:
  - pwd
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=~/builds/ruboto/ruboto/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2,9 --no-ui --force

rvm:
#  - "1.8.7"
  - "1.9.3"
#  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-18mode
#  - rbx-19mode

jdk:
#   - oraclejdk6
   - oraclejdk7
#   - openjdk7
#   - openjdk6

#env:
#  - FOO=foo BAR=bar
#  - FOO=bar BAR=foo

script: ./matrix_test.sh
